---
- name: folder permission
#  debug: msg='{{item}}'
  file: 
    path: '{{item}}'
    state: directory
    owner: '{{mongouser}}'
    group: '{{mongouser}}'
  become: true
  with_items:
    - '{{datapath}}'
    - '{{logpath}}'
- name: copy configuration parameter
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  become: true
# selinux의 policy를 설정하기 위해서는 policycoreutils-python 가 설치되어 있어야 한다고 나옴. common role에 넣어야 할 듯.
- name: install policycoreutils-python for SELinux
  yum:
    name: policycoreutils-python
    state: present
  become: true
# CentOS는 SELinux가 enable되어 있다고 함. logpath와 datapath에 대해서 mongod가 사용할 수 있도록 file context를 수정해야 함
#chcon -Rv --type=mongod_log_t /data0/mongodb
- name: enable log folder writable by mongod
  sefcontext:
    target: '{{logpath}}'
    setype: mongod_log_t
    state: present
  become: true
#chcon -Rv --type=mongod_var_lib_t /data1/mongo/
- name: enable db folder writable by mongod
  sefcontext:
    target: '{{datapath}}'
    setype: mongod_var_lib_t
    state: present
  become: true
